CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password_digest TEXT NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  sub VARCHAR(255) NOT NULL,
  contant TEXT NOT NULL,
  img VARCHAR(255) NOT NULL,
  uploader VARCHAR(255) NOT NULL,
  uptime VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  authority VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS issues (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  sub VARCHAR(255) NOT NULL,
  contant Te(255) NOT NULL,
  img VARCHAR(255) NOT NULL,
  uploader VARCHAR(255) NOT NULL,
  uptime VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  sub_category VARCHAR(255)
);